# VERSIONE application.properties - sort of backup
#  spring.application.name=python-embedding
#
#  spring.datasource.url=jdbc:mysql://localhost:3306/diabetes-prediction
#  spring.datasource.username=root
#  spring.datasource.password=Leonardo42!
#  spring.datasoruce.driver-class-name=com.mysql.cj.jdbc.Driver

server:
  port: 8081
  servlet:
    context-path: /diabetes-prediction

spring:
  application:
    name: python-embedding
  datasource:
    url: jdbc:mysql://localhost:3306/diabetes-prediction
    username: root
    password: Leonardo42!
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


app:
  datasource:
    dbname: "`diabetes-prediction`"
    table-name: "${app.datasource.dbname}.`pazienti-diabetici`"
    batch-size: 1000
  data-analisys:
    unbalance-fraction: 0.55
    smote-factor: 2
